# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "30bc22ddc9c13fb825d24da151a0c5a6"
name = "test-app-remix"
handle = "test-app-remix-9"
application_url = "https://novels-college-memphis-worm.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-f4b3820b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://novels-college-memphis-worm.trycloudflare.com/auth/callback",
  "https://novels-college-memphis-worm.trycloudflare.com/auth/shopify/callback",
  "https://novels-college-memphis-worm.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
